### ISSUE TITLE
Do we really need to allow this frame in handshake packets?

### ISSUE THREAD

**Issue by huitema** [marten-seemann/draft-seemann-quic-address-discovery#21]
Handshake packets are received by the client *before* the negotiation of transport parameters completes, thus the client does not know whether the frames are authorized or not. Disallowing these frames in handshake packets would simplify the implementation, with very little impact on performance.

**Comment by marten-seemann** [comment]
Makes sense. You can just send them in 0.5-RTT data instead, potentially in the same (coalesced) packet.
