### ISSUE TITLE
Transport Parameter should reserve value 0 for Unsupported

### ISSUE THREAD

**Issue by huitema** [marten-seemann/draft-seemann-quic-address-discovery#24]
The current definition of the `address_discovery` parameter specifies 3 possible values:

0. The node is willing to provide address observations to its peer, but is not interested in receiving address observations itself.
1. The node is interested in receiving address observations, but it is not willing to provide address observations.
2. The node is interested in receiving address observations, and it is willing to provide address observations.

There is a hidden value, "parameter absent", that means "address discovery is not supported." That requires managing an additional boolean in the implementation, to specify to not send this parameter.

I think that it would be simpler to explicitly have 4 values:

0. Address discovery is not supported. This is the default value if the parameter is absent.
1. The node is willing to provide address observations to its peer, but is not interested in receiving address observations itself.
2. The node is interested in receiving address observations, but it is not willing to provide address observations.
3. The node is interested in receiving address observations, and it is willing to provide address observations.

 If the value is 0, the implementation should not send the parameter.

This does not create any additional overhead, since we always need one byte to encode the value.

**Comment by marten-seemann** [comment]
I'm not sure I understand the problem. How you store this in your implementation is independent from how we encode things on the wire. It's totally reasonable to have an enum with the 4 states you describe to represent the state of this extension.

**Comment by huitema** [comment]
That's indeed what I do, 4 values internally, 3 values on the wire. But it is a bit of gratuitous complexity. 4 values on the wire would be just as easy to process as 3 values, and would simplify the code. Not a huge deal, of course, but I did get confused when writing my unit test, and other developers could be.

**Comment by marten-seemann** [comment]
Do we have any precedent for explicitly encoding "I don't support this extension" in other QUIC extensions? I see little value in explicitly encoding this on the wire.

**Comment by huitema** [comment]
RFC 9218, QUIC Datagrams, advertises the maximum length of a datagram frame. Value 0 means "not supported."

**Comment by marten-seemann** [comment]
That's 9221, and I interpret the RFC differently. It just means that you don't support _receiving_ DATAGRAM frames.
