### ISSUE TITLE
0-RTT

### ISSUE THREAD

**Issue by martinthomson** [marten-seemann/draft-seemann-quic-address-discovery#3]
I am fairly confident that these frames are safe to send in 0-RTT.

**Comment by marten-seemann** [comment]
The draft states that the frames allowed in the application-data packet number space (which includes both 0-RTT and 1-RTT), and it also requires endpoints to remember the value of the transport parameter for 0-RTT.

Do you have an editorial suggestion to make it clearer that these frames are allowed in 0-RTT?

**Comment by huitema** [comment]
We do have text in Section 3:

_When using 0-RTT, both endpoints MUST remember the value of this transport parameter. This allows sending the frame defined by this extension in 0-RTT packets. If 0-RTT data is accepted by the server, the server MUST NOT disable this extension or change the value on the resumed connection_

I think that does address the issue. @martinthomson, do you agree?

**Comment by martinthomson** [comment]
That would do it, yes.
