### ISSUE TITLE
acknowledge draft-pauly-quic-address-extension

### ISSUE THREAD

**Issue by marten-seemann** [marten-seemann/draft-seemann-quic-address-discovery#30]
David Schinazi suggested acknowledging https://datatracker.ietf.org/doc/draft-pauly-quic-address-extension/. I was not aware of this draft when I wrote up the first version of my draft (as far as I can tell, it was never discussed on the QUIC mailing list), but the idea is quite similar.

**Comment by huitema** [comment]
Yes. It is indeed similar, and deserves to be acknowledged.
