### ISSUE TITLE
Repeated requests

### ISSUE THREAD

**Issue by martinthomson** [marten-seemann/draft-seemann-quic-address-discovery#4]
What if an endpoint receives two requests from different source addresses?

**Comment by marten-seemann** [comment]
That’s ok, and in fact, that’s expected when the connection is probing different paths. The sequence number allows the requests and responses to be distinguished from each other.

**Comment by martinthomson** [comment]
I was specifically talking about the case where the same sequence number appears.

I think that you want to say that the sequence number (really, a request ID) is just there to help the requester distinguish answers.  The responder just echoes the value back (and responds to every request it receives, even apparent duplicates).

**Comment by marten-seemann** [comment]
I agree. This makes a lot of sense, and will become a lot more apparent once we rename the field to request ID.
