### ISSUE TITLE
Sequence number or just unique?

### ISSUE THREAD

**Issue by martinthomson** [marten-seemann/draft-seemann-quic-address-discovery#5]
Because the sequence number is simply echoed, it might not need to be monotonic.  It should be enough to just have it be unique.  Obviously, a counter is the easiest method to use, but given typical usage, it might be OK to send the same value always.  If the endpoint that responds does so unconditionally (without collapsing duplicates, see #4), then this will probably be enough for most endpoints to get what they need (that is, the set of reflexive addresses they have).

**Comment by marten-seemann** [comment]
It’s correct that we only need a unique value, but using a sequence number makes it easier to detect the error condition (when your peer sends you a response for a request you didn’t send).

Maybe we should just point that out, and rename it to “Request ID” or something like that?
