### ISSUE TITLE
consider moving away from request-response

### ISSUE THREAD

**Issue by marten-seemann** [marten-seemann/draft-seemann-quic-address-discovery#7]
On the mailing list, Igor proposed to move away from a request-response scheme, and have nodes report the observed address without being requested to do so.

We could change the logic such that negotiating this extension means that:
1. Endpoints are expected to inform their peer of the observed address after completion of the handshake (or maybe even in Handshake packets during the handshake?).
2. Include a NEW_OBSERVED_ADDRESS frame in probing packets on a new path.
3. Send a NEW_OBSERVED_ADDRESS whenever the remote address changes on a path (e.g. due to a NAT rebinding).
 
We might use the value of the transport parameter to distinguish between "I'm willing to report your address" and "I'm requesting that you send me NEW_OBSERVED_ADDRESS frames".

**Comment by huitema** [comment]
That's cool, but then the NEW OBSERVED ADDRESS needs to be tied to a path number. Otherwise, the client will not be able to tell. 
Maybe just copy the CID of the packet for which the new address was observed?

**Comment by marten-seemann** [comment]
@huitema I don’t think that’s necessary. Your QUIC stack will know the path it received the from on, won’t it?

**Comment by huitema** [comment]
No, because you do not want to constraint the address observed frames to be on the "same path". Especially when doing discovery/ice, because there id no guarantee that the "same path" is working in both directions.

**Comment by marten-seemann** [comment]
You're right. I hadn't considered unidirectional paths. Adding the CID would indeed be a solution, but there are downsides to coupling ourselves to the CID state machine: the CID might have been retired in the mean time. Not saying that this isn't possible, but we need to think about corner cases very carefully.

**Comment by huitema** [comment]
The CID is only retired if the client who sent the traffic decides to retire it. In that case, the client won't be able to match the IP address with a path, which is not good but also not the end of the world.
